windows_task:
  windows_container:
    image: cirrusci/windowsservercore:2016
  env:
    CIRRUS_SHELL: powershell
  yarn_script:
    - Write-Host "Downloading..."
    - $msiPath = "$env:TEMP\yarn.msi"
    - (New-Object Net.WebClient).DownloadFile('https://yarnpkg.com/latest.msi', $msiPath)
    - Write-Host "Installing..."
    - cmd /c start /wait msiexec /i "$msiPath" /quiet
  environment:
    AWS_ACCESS_KEY_ID: ENCRYPTED[9045ce6b930edefbd4c14d388a3e963cf6bcc938815aebcb0b331800bd0c3f76587533ce9207e7989138a7ed9afd7159]
    AWS_SECRET_ACCESS_KEY: ENCRYPTED[3fd7909c3b2e089d38da979bb3420cd7d6c68fc757129aef403f5f1f866183459afc5938d2fcb6403d57ba53543345ff]
  node_modules_cache:
    folder: node_modules
    fingerprint_script: print yarn.lock
    populate_script: yarn install
  build_script: yarn run build
  publish_script: yarn run release

mac_task:
  osx_instance:
    image: high-sierra-xcode-9.4.1
  yarn_script:
    - brew install yarn
  environment:
    AWS_ACCESS_KEY_ID: ENCRYPTED[9045ce6b930edefbd4c14d388a3e963cf6bcc938815aebcb0b331800bd0c3f76587533ce9207e7989138a7ed9afd7159]
    AWS_SECRET_ACCESS_KEY: ENCRYPTED[3fd7909c3b2e089d38da979bb3420cd7d6c68fc757129aef403f5f1f866183459afc5938d2fcb6403d57ba53543345ff]
  node_modules_cache:
    folder: node_modules
    fingerprint_script: cat yarn.lock
    populate_script: yarn install
  build_script: yarn run build
  publish_script: yarn run release

linux_task:
  container:
    image: node:latest
  environment:
    AWS_ACCESS_KEY_ID: ENCRYPTED[9045ce6b930edefbd4c14d388a3e963cf6bcc938815aebcb0b331800bd0c3f76587533ce9207e7989138a7ed9afd7159]
    AWS_SECRET_ACCESS_KEY: ENCRYPTED[3fd7909c3b2e089d38da979bb3420cd7d6c68fc757129aef403f5f1f866183459afc5938d2fcb6403d57ba53543345ff]
  node_modules_cache:
    folder: node_modules
    fingerprint_script: cat yarn.lock
    populate_script: yarn install
  presetup_script: snap install snapcraft --classic
  build_script: yarn run build
  publish_script: yarn run release
