language: node_js
branches:
  only:
    - master
matrix:
  allow_failures:
    - os: windows
  fast_finish: true
  include:
    - name: "build on windows"
      os: windows
    - name: "build on mac"
      os: osx
    - name: "build on linux"
      os: linux
sudo: false
node_js:
- '10'
cache: yarn
before_install:
  - if [ "$TRAVIS_OS_NAME" == "windows" ]; then powershell -command 'Set-MpPreference -DisableRealtimeMonitoring $true'; fi
install:
  # - cd ./packages/audiobookplayer
  - yarn install
env:
  - DEBUG=electron-builder BUILD_COMMIT_SHA1="$TRAVIS_COMMIT" NODE_ENV=production NPM_CONFIG_PRODUCTION=false
script:
  - echo $TRAVIS_COMMIT
  - echo $BUILD_COMMIT_SHA1
  - yarn run build
  - if [ "$TRAVIS_OS_NAME" == "windows" ]; then powershell -command 'yarn release:win'; fi
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then yarn package:mac; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then yarn package:linux; fi